version: '3.9'
services:
  cloudflare-firewall-dynip:
    image: benscobie/cloudflare-firewall-dynip:latest
    container_name: cloudflare-firewall-dynip
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /YOUR/PATH/HERE/config.json:/config.json
    restart: unless-stopped
